"""Add department and class_name fields

Revision ID: 22c6b2419cf5
Revises: 
Create Date: 2025-10-31 09:08:15.959277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c6b2419cf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('teacher_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_details', schema=None) as batch_op:
        batch_op.drop_column('department')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
