"""Rename acodemic_score to academic_score

Revision ID: 9876a5762856
Revises: 22c6b2419cf5
Create Date: 2025-12-07 14:28:06.465667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9876a5762856'
down_revision = '22c6b2419cf5'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    insp = inspect(bind)
    columns = [col['name'] for col in insp.get_columns('students')]
    
    with op.batch_alter_table('students', schema=None) as batch_op:
        # Conditional alters (skip if type matches or column missing)
        try:
            batch_op.alter_column('behavior_score', existing_type=mysql.INTEGER(), type_=sa.Float(), existing_nullable=True)
        except:
            pass
        try:
            batch_op.alter_column('course', existing_type=mysql.VARCHAR(length=255), type_=sa.String(length=100), existing_nullable=True)
        except:
            pass
        try:
            batch_op.alter_column('gender', existing_type=mysql.VARCHAR(length=20), type_=sa.String(length=10), existing_nullable=True)
        except:
            pass
        try:
            batch_op.alter_column('marital_status', existing_type=mysql.VARCHAR(length=255), type_=sa.String(length=50), existing_nullable=True)
        except:
            pass
        try:
            batch_op.alter_column('application_mode', existing_type=mysql.INTEGER(), type_=sa.String(length=50), existing_nullable=True)
        except:
            pass
        try:
            batch_op.alter_column('scholarship_holder', existing_type=mysql.TINYINT(display_width=1), type_=sa.String(length=10), existing_server_default=sa.text("'0'"), existing_nullable=True)
        except:
            pass
        try:
            batch_op.alter_column('debtor', existing_type=mysql.TINYINT(display_width=1), type_=sa.String(length=10), existing_server_default=sa.text("'0'"), existing_nullable=True)
        except:
            pass
        try:
            batch_op.alter_column('tuition_fees_up_to_date', existing_type=mysql.TINYINT(display_width=1), type_=sa.String(length=10), existing_server_default=sa.text("'0'"), existing_nullable=True)
        except:
            pass
        
        # FK handling
        # Conditional drop old index
        indexes = [idx['name'] for idx in insp.get_indexes('students')]
        if 'students_ibfk_1' in indexes:
            batch_op.drop_index('students_ibfk_1')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        
        # Conditional drops
        drop_cols = ['application_order', 'cu1_no_evaluation', 'father_education', 'target', 'admission_grade', 'cu1_credited', 'unemployment_rate', 'gdp', 'class_name', 'previous_qualification', 'mother_education', 'nationality', 'cu2_evaluations', 'previous_qualification_grade', 'Academic_Score', 'father_occupation', 'mother_occupation', 'day_evening', 'cu2_no_evaluation', 'cu2_credited', 'cu1_evaluations', 'inflation_rate']
        for col in drop_cols:
            if col in columns:
                batch_op.drop_column(col)
        
        # Conditional add
        if 'academic_score' not in columns:
            batch_op.add_column(sa.Column('academic_score', sa.Integer(), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inflation_rate', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cu1_evaluations', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cu2_credited', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cu2_no_evaluation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day_evening', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mother_occupation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('father_occupation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Academic_Score', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_qualification_grade', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cu2_evaluations', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nationality', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mother_education', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_qualification', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('gdp', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('unemployment_rate', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cu1_credited', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admission_grade', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('target', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('father_education', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cu1_no_evaluation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('application_order', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('students_ibfk_1'), ['user_id'], unique=False)
        batch_op.alter_column('tuition_fees_up_to_date',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('debtor',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('scholarship_holder',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('application_mode',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('course',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('behavior_score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('academic_score')

    # ### end Alembic commands ###
