version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ai_dropout_prediction_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dropout_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: ai_dropout_backend
    restart: always
    depends_on:
      - mysql
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DB: dropout_db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: ai_dropout_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
