"""Rename acodemic_score to academic_score

Revision ID: 9876a5762856
Revises: 22c6b2419cf5
Create Date: 2025-12-07 14:28:06.465667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9876a5762856'
down_revision = '22c6b2419cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('behavior_score',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('course',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('application_mode',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('scholarship_holder',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('debtor',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('tuition_fees_up_to_date',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('students_ibfk_1'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('application_order')
        batch_op.drop_column('cu1_no_evaluation')
        batch_op.drop_column('father_education')
        batch_op.drop_column('target')
        batch_op.drop_column('admission_grade')
        batch_op.drop_column('cu1_credited')
        batch_op.drop_column('unemployment_rate')
        batch_op.drop_column('gdp')
        batch_op.drop_column('class_name')
        batch_op.drop_column('previous_qualification')
        batch_op.drop_column('mother_education')
        batch_op.drop_column('nationality')
        batch_op.drop_column('cu2_evaluations')
        batch_op.drop_column('previous_qualification_grade')
        batch_op.drop_column('Academic_Score')
        batch_op.add_column(sa.Column('academic_score', mysql.INTEGER(), nullable=True))
        batch_op.drop_column('father_occupation')
        batch_op.drop_column('mother_occupation')
        batch_op.drop_column('day_evening')
        batch_op.drop_column('cu2_no_evaluation')
        batch_op.drop_column('cu2_credited')
        batch_op.drop_column('cu1_evaluations')
        batch_op.drop_column('inflation_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inflation_rate', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cu1_evaluations', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cu2_credited', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cu2_no_evaluation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day_evening', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mother_occupation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('father_occupation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Academic_Score', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_qualification_grade', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cu2_evaluations', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nationality', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mother_education', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_qualification', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('gdp', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('unemployment_rate', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cu1_credited', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admission_grade', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('target', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('father_education', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cu1_no_evaluation', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('application_order', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('students_ibfk_1'), ['user_id'], unique=False)
        batch_op.alter_column('tuition_fees_up_to_date',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('debtor',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('scholarship_holder',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('application_mode',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('course',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('behavior_score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('academic_score')

    # ### end Alembic commands ###
